---
image: centos:8

stages:
  - analysis
  - test

before_script:
  - yum -q -y install python3-pip python3-devel
  - python3 -m pip -q install --upgrade pip
  - python3 -m pip -q install -r requirements.txt
  - python3 -m pip -q install -r test-requirements.txt

lint:
  stage: analysis
  script:
    - mkdir ./pylint
    - pylint --output-format=text svetlana/*.py | tee ./pylint/pylint.log || pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=lint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/

test:
  stage: test
  script:
    - pytest --cov=svetlana -v
  coverage: '/TOTAL.*\s+(\d+%)$/'
